### ISSUE TITLE
the first two links are not functioning correctly

### ISSUE THREAD

**Issue by lodado** [dannyhw/storybook-chromatic-link-comment#116]
Hello, thank you for creating such useful GitHub actions.

the last comment on https://github.com/abcdefghijklmn2/pokitoki/pull/15, 
it seems that the first two links are not functioning correctly: (move to pr page) 

![image](https://github.com/dannyhw/storybook-chromatic-link-comment/assets/40421183/869addc7-c1d6-4832-be21-c47287d78d1a)

Could you advise on how to fix this? Thank you.
Below is my GitHub action.yml code.

```
# .github/workflows/chromatic.yml

name: "Chromatic-on-pr"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install
      
      - name: build repositories
        run: pnpm build --filter=\!web --filter=\!docs

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/docs
      
      - name: Storybook Link
        uses: dannyhw/storybook-chromatic-link-comment@v0.10
        with:
          app-id: ${{ secrets.CHROMATIC_APP_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
